# Generated by Django 5.1.5 on 2025-02-09 16:49

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='شناسه کاربر')),
                ('table_id', models.IntegerField(verbose_name='شناسه میز')),
                ('number_of_seat', models.IntegerField(validators=[utils.seats_number_validator], verbose_name='تعداد نفرات')),
                ('order_price', models.IntegerField(verbose_name='قیمت سفارش')),
                ('order_state', models.CharField(choices=[('D', 'سفارش انجام شده'), ('S', 'سفارش ثبت شده'), ('C', 'سفارش لغو شده')], default='S', max_length=1, verbose_name='وضعیت سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروز شده در')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='نام میز')),
                ('seats_number', models.IntegerField(validators=[utils.seats_number_validator], verbose_name='تعداد صندلی')),
                ('table_state', models.CharField(choices=[('R', 'رزرو شده'), ('A', 'در دسترس')], default='A', max_length=1, verbose_name='وضعیت میز')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='ایجاد شده در')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروز شده در')),
            ],
            options={
                'verbose_name': 'میز',
                'verbose_name_plural': 'میزها',
                'ordering': ['-id'],
            },
        ),
    ]
