version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres-django-restaurant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pars1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: restaurant_redis
    ports:
      - "6380:6379"

  celery_worker:
    build: .
    container_name: restaurant_celery_worker
    command: celery -A restaurant worker --loglevel=info
    depends_on:
      - redis
      - app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery_beat:
    build: .
    container_name: restaurant_celery_beat
    command: celery -A restaurant beat --loglevel=info
    depends_on:
      - redis
      - app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  app:
    build:
      context: .
    container_name: restaurant
    env_file:
      - ../.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: pars1234
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver localhost:8000"

volumes:
  postgres_data: